name: Bug Report
description: File a bug report
title: "[Bug] "
labels: ["bug", "triage"]
assignees:
    - octocat
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report!
    - type: textarea
      id: addon
      attributes:
          label: Addon
          description: Which Addon of Mine are you reporting about?
      validations:
          required: true
    - type: textarea
      id: what-happened
      attributes:
          label: What happened?
          description: What happened and what did you expect to happen
          value: "... happened."
      validations:
          required: true
    - type: dropdown
      id: version
      attributes:
          label: What Discord version do you have this issue on?
          multiple: true
          options:
              - Stable
              - PTB
              - Canary
              - Web
    - type: textarea
      id: logs
      attributes:
          label: Logs
          description: Please copy and paste any relevant log/console output.
          render: shell
    - type: checkboxes
      id: terms
      attributes:
          label: Code of Conduct
          description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/TheCommieAxolotl/BetterDiscord-Stuff/blob/main/CODE_OF_CONDUCT.md)
          options:
              - label: I agree to follow this project's Code of Conduct
                required: true
